# Netlify configuration for PRISM Analytics
# Executive inventory dashboard with React + TypeScript + Vite

[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "./"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment settings
[context.production]
  command = "npm install && npm run build"
  publish = "dist"
  
[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

# Deploy Preview settings
[context.deploy-preview]
  command = "npm install && npm run build"
  publish = "dist"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "preview"

# Branch deploys
[context.branch-deploy]
  command = "npm install && npm run build"
  publish = "dist"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "development"